import { DashboardData } from './types';

export const mockData: DashboardData = {
  lastUpdated: new Date().toISOString(),
  reps: [
    {
      name: 'Alex',
      weeklyData: [
        {
          week: 'January 1 2026',
          weekDate: new Date('2026-01-01'),
          introCallsScheduled: 8,
          introCallsTaken: 6,
          showUpRate: 75,
          acceptanceQualityRate: 83.33,
          accountsAudited: 5,
          proposalsPitched: 2,
          dealsClosed: 1,
          proposalRate: 40,
          closeRate: 50,
          thisMonthMRR: 2500,
          mrrPerCallTaken: 416.67,
          mrrPerAudit: 500,
          mrrPerSales: 2500,
        },
        {
          week: 'January 9 2026',
          weekDate: new Date('2026-01-09'),
          introCallsScheduled: 12,
          introCallsTaken: 12,
          showUpRate: 100,
          acceptanceQualityRate: 33.33,
          accountsAudited: 4,
          proposalsPitched: 4,
          dealsClosed: 0,
          proposalRate: 100,
          closeRate: 0,
          thisMonthMRR: 2500,
          mrrPerCallTaken: 208.33,
          mrrPerAudit: 625,
          mrrPerSales: 0,
        },
        {
          week: 'January 17 2026',
          weekDate: new Date('2026-01-17'),
          introCallsScheduled: 7,
          introCallsTaken: 4,
          showUpRate: 57.14,
          acceptanceQualityRate: 75,
          accountsAudited: 3,
          proposalsPitched: 3,
          dealsClosed: 3,
          proposalRate: 100,
          closeRate: 100,
          thisMonthMRR: 11000,
          mrrPerCallTaken: 2900,
          mrrPerAudit: 3933.33,
          mrrPerSales: 3933.33,
        },
        {
          week: 'January 24 2026',
          weekDate: new Date('2026-01-24'),
          introCallsScheduled: 11,
          introCallsTaken: 5,
          showUpRate: 45.45,
          acceptanceQualityRate: 100,
          accountsAudited: 5,
          proposalsPitched: 5,
          dealsClosed: 2,
          proposalRate: 100,
          closeRate: 40,
          thisMonthMRR: 5000,
          mrrPerCallTaken: 1000,
          mrrPerAudit: 1000,
          mrrPerSales: 2500,
        },
        {
          week: 'January 31 2026',
          weekDate: new Date('2026-01-31'),
          introCallsScheduled: 11,
          introCallsTaken: 5,
          showUpRate: 45.45,
          acceptanceQualityRate: 100,
          accountsAudited: 5,
          proposalsPitched: 5,
          dealsClosed: 2,
          proposalRate: 100,
          closeRate: 40,
          thisMonthMRR: 5000,
          mrrPerCallTaken: 1000,
          mrrPerAudit: 1000,
          mrrPerSales: 2500,
        },
      ],
      monthlySummaries: [
        {
          month: 'January 2026',
          totalCallsScheduled: 49,
          totalCallsTaken: 32,
          showUpRate: 65.31,
          acceptanceQualityRate: 78.33,
          totalAccountsAudited: 22,
          totalProposals: 19,
          totalClosed: 8,
          proposalRate: 86.36,
          closeRate: 42.11,
          totalMRR: 26000,
          mrrPerCallTaken: 812.50,
          mrrPerAudit: 1181.82,
          mrrPerSales: 3250,
        },
      ],
      quarterlySummaries: [
        {
          quarter: 'Q1 2026',
          months: [],
          totalCallsScheduled: 49,
          totalCallsTaken: 32,
          showUpRate: 65.31,
          acceptanceQualityRate: 78.33,
          totalAccountsAudited: 22,
          totalProposals: 19,
          totalClosed: 8,
          proposalRate: 86.36,
          closeRate: 42.11,
          totalMRR: 26000,
          mrrPerCallTaken: 812.50,
          mrrPerAudit: 1181.82,
          mrrPerSales: 3250,
        },
      ],
    },
    {
      name: 'Dom',
      weeklyData: [
        {
          week: 'January 1 2026',
          weekDate: new Date('2026-01-01'),
          introCallsScheduled: 8,
          introCallsTaken: 6,
          showUpRate: 75,
          acceptanceQualityRate: 83.33,
          accountsAudited: 5,
          proposalsPitched: 2,
          dealsClosed: 1,
          proposalRate: 40,
          closeRate: 50,
          thisMonthMRR: 2500,
          mrrPerCallTaken: 416.67,
          mrrPerAudit: 500,
          mrrPerSales: 2500,
        },
        {
          week: 'January 9 2026',
          weekDate: new Date('2026-01-09'),
          introCallsScheduled: 12,
          introCallsTaken: 12,
          showUpRate: 100,
          acceptanceQualityRate: 33.33,
          accountsAudited: 4,
          proposalsPitched: 4,
          dealsClosed: 0,
          proposalRate: 100,
          closeRate: 0,
          thisMonthMRR: 2500,
          mrrPerCallTaken: 208.33,
          mrrPerAudit: 625,
          mrrPerSales: 0,
        },
        {
          week: 'January 17 2026',
          weekDate: new Date('2026-01-17'),
          introCallsScheduled: 7,
          introCallsTaken: 4,
          showUpRate: 57.14,
          acceptanceQualityRate: 75,
          accountsAudited: 3,
          proposalsPitched: 3,
          dealsClosed: 3,
          proposalRate: 100,
          closeRate: 100,
          thisMonthMRR: 11000,
          mrrPerCallTaken: 2900,
          mrrPerAudit: 3933.33,
          mrrPerSales: 3933.33,
        },
        {
          week: 'January 24 2026',
          weekDate: new Date('2026-01-24'),
          introCallsScheduled: 11,
          introCallsTaken: 5,
          showUpRate: 45.45,
          acceptanceQualityRate: 100,
          accountsAudited: 5,
          proposalsPitched: 5,
          dealsClosed: 2,
          proposalRate: 100,
          closeRate: 40,
          thisMonthMRR: 5000,
          mrrPerCallTaken: 1000,
          mrrPerAudit: 1000,
          mrrPerSales: 2500,
        },
        {
          week: 'January 31 2026',
          weekDate: new Date('2026-01-31'),
          introCallsScheduled: 11,
          introCallsTaken: 5,
          showUpRate: 45.45,
          acceptanceQualityRate: 100,
          accountsAudited: 5,
          proposalsPitched: 5,
          dealsClosed: 2,
          proposalRate: 100,
          closeRate: 40,
          thisMonthMRR: 5000,
          mrrPerCallTaken: 1000,
          mrrPerAudit: 1000,
          mrrPerSales: 2500,
        },
      ],
      monthlySummaries: [
        {
          month: 'January 2026',
          totalCallsScheduled: 49,
          totalCallsTaken: 32,
          showUpRate: 65.31,
          acceptanceQualityRate: 78.33,
          totalAccountsAudited: 22,
          totalProposals: 19,
          totalClosed: 8,
          proposalRate: 86.36,
          closeRate: 42.11,
          totalMRR: 26000,
          mrrPerCallTaken: 812.50,
          mrrPerAudit: 1181.82,
          mrrPerSales: 3250,
        },
      ],
      quarterlySummaries: [
        {
          quarter: 'Q1 2026',
          months: [],
          totalCallsScheduled: 49,
          totalCallsTaken: 32,
          showUpRate: 65.31,
          acceptanceQualityRate: 78.33,
          totalAccountsAudited: 22,
          totalProposals: 19,
          totalClosed: 8,
          proposalRate: 86.36,
          closeRate: 42.11,
          totalMRR: 26000,
          mrrPerCallTaken: 812.50,
          mrrPerAudit: 1181.82,
          mrrPerSales: 3250,
        },
      ],
    },
  ],
};
